# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88f2323d6fe2eb58ce7c820f5aa1f05ffe8027b8966f49b0c263a14f7e749d21c8621fb9fb2b7d577ececadb75c8128981af8cd5a3cf156c67bbe925deb4769b

test:
  secret_key_base: 8dbe2d00673f0f287d9ec04d94c7408f8aa70ee01d12e8ac1dce26a408f1b31f949995291df709ee6794302553931728faf3e2d01c7b84a1a75b9cac2825d925

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
